[package]
name = "woomer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.6"
raylib = "5.5.1"
xcap = "0.6.1"
[features]
dev = []
